# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'botsocial' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for botsocial
  pod 'PINRemoteImage', '3.0.0-beta.13'
   pod 'SnapKit', '~> 4.0.0'
   pod 'Firebase/Core'
   pod 'FirebaseUI'
   pod "Sharaku"
  target 'botsocialTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'botsocialUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
